#!/usr/bin/env ruby
#if less than 10, divide by 10

value = 9

if value < 10
	value /= 10
end


=BEGIN

do all of the cards as numbers?

what about aces and straights?

A1 2 3 4 5 6 7 8 9 100 110 120 130 A140



=END
